spring:
  application:
    name: meow-express
  datasource:
    url: jdbc:mysql://localhost:3306/meow_express?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080